<div class="modal-dialog modal-md">
    <div class="modal-content">
        <div class="d-flex justify-content-between p-3 pb-0">
            <h5>{{ $title }}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body pt-0">
            <form action="{{ $action ?? '' }}" method="POST" class="ajax-form-modal">
                @csrf
                <p class="m-0 text-muted">Each time you log in, you will need to verify your identity using the authenticator app to generate a verification code.</p>
                <div class="mb-3 mt-3">
                    <p class="text-muted fw-bold"><span class="badge bg-secondary bg-opacity-10 text-secondary me-1">Step 1</span> Scan the QR code</p>
                    <div class="d-flex justify-content-between gap-2 bg-light p-2 rounded">
                        <div style="width: 120px; height: 120px;">
                            {!! $qrcode !!}
                        </div>
                        <div class="flex-grow-1">
                            <p class="text-muted">Can't scan the QR code?</p>
                            <p class="text-muted">You can enter the code manually:</p>
                            <p class="fw-bold">{{ $user->two_factor_secret }}</p>
                            <button type="button" class="btn btn-light p-0 px-1"><i class="fa-solid fa-clipboard me-1"></i> Copy code</button>
                        </div>
                    </div>
                </div>
                <div class="mb-3 mt-3">
                    <p class="text-muted fw-bold"><span class="badge bg-secondary bg-opacity-10 text-secondary me-1">Step 2</span> Get verification code</p>
                    <p class="text-muted">Enter the 6-digit code generated by your authenticator app.</p>
                    <label class="text-muted fw-bold form-label required">Enter verification code</label>
                    <input type="text" id="authenticator-code" class="form-control form-control-sm" placeholder="123456" required autofocus maxlength="6" pattern="[0-9]{6}" name="code">
                </div>
                <div class="justify-content-end d-flex gap-2">
                    <button type="button" class="btn btn-light btn-sm" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary btn-sm">Confirm</button>
                </div>
            </form>
        </div>
    </div>
</div>
